name: inputdemo
on: 
  workflow_dispatch:
    inputs:
      environments:
        description: this is input demo
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - test
      tags:
        description: this is tag
        required: true
        default: 1.0.0

jobs:
  inputs-demo:
    runs-on: self-hosted
    steps:
      - name: Deploy the app
        run: echo "Depoly the ${{inputs.tags}} application to ${{inputs.environments}}"
